manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/romansavrulin
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: cont-layer
      import: app/west.yml
  self:
    path: config
